function f_new = FL_HT2D2V_handle_clamp( ...
        i,j,p,q, ...
        f_preT, phi_ht,phix_ht,phixy_ht, ...
        x_extend, k_mod_1, k_mod_2, ...
        h_mesh, N_mesh,dom_len, ...
        n_ghost, dt, H)

    % normalize inputs
    vars = {i,j,p,q};
    vars = cellfun(@(x) x(:), vars, 'UniformOutput', false);
    [i,j,p,q] = deal(vars{:});
    N = max(cellfun(@length, vars));

    index = [i.*ones(N,1), j.*ones(N,1), p.*ones(N,1), q.*ones(N,1)];

    % mask for zero values
    zero_mask = (index(:,2) == 1) & (index(:,4) == 1);

    % vectorized HT evaluation
    f_val = get_val_ht_2D2V_SG( ...
        f_preT, ...
        x_extend{1}(n_ghost + index(:,1), 2), ...
        x_extend{2}(n_ghost + index(:,3), 2), ...
        index(:,2), ...
        index(:,4));

    % preallocate
    phi_val = zeros(N,1);

    % unavoidable pointwise phase (already optimized internally)
    for l = 1:N
        if ~zero_mask(l)
            phi_val(l) = get_phi_clamp( ...
                phi_ht,phix_ht,phixy_ht, l, index, x_extend, n_ghost, ...
                k_mod_1(index(l,2)), ...
                k_mod_2(index(l,4)), ...
                H, h_mesh, N_mesh, dom_len);
        end
    end
    
    % f_new = f_val.*exp(1i/H * dt.*phi_val);
    % assemble
    f_new = zeros(N,1);
    f_new(~zero_mask) = ...
        f_val(~zero_mask) .* exp(1i/H * dt .* phi_val(~zero_mask));
end
