function htd = zeros(tree)
%ZEROS Constructs an HTD structure representing an all-zero tensor.
%
%   htd = ht.zeros(tree)
%
%   Input:
%       tree - a tree struct generated by make_tree(...)
%
%   Output:
%       htd - a struct with fields:
%             .tree   : the input tree
%             .U      : leaf basis matrices (all-zero columns)
%             .B      : core tensors (1×1×1 zeros at non-leaf nodes)
%             .rank   : row vector of ones

    N = size(tree.children, 1);

    htd.tree = tree;
    htd.rank = ones(1, tree.N_node);
    htd.U = cell(1, tree.N_node);
    htd.B = cell(1, tree.N_node);

    % Assign U at leaf nodes via dim2ind
    for d = 1: tree.orders(1)
        node = tree.dim2ind(d);
        htd.U{node} = zeros(tree.modesizes(d), 1);
    end

    % Assign B at nonleaf nodes directly
    htd.B(tree.nonleaf) = {zeros(1, 1, 1)};
end
