function f_new = FL_HT3D3V_handle_vec( ...
        i, j, p, q, k, r, ...
        f_preT, phi_ht, phix_ht, phi_cross, ...
        x_extend, k_mod_1, k_mod_2, k_mod_3, ...
        h_mesh, N_mesh, ...
        n_ghost, dt, H)

    % Normalize all input indices to column vectors.
    vars = {i,j,p,q,k,r};
    vars = cellfun(@(x) x(:), vars, 'UniformOutput', false);
    [i,j,p,q,k,r] = deal(vars{:});
    N = max(cellfun(@length, vars));

    index = [i.*ones(N,1), j.*ones(N,1), ...
             p.*ones(N,1), q.*ones(N,1), ...
             k.*ones(N,1), r.*ones(N,1)];

    % Mask the zero Fourier velocity mode.
    zero_mask = (index(:,2) == 1) & (index(:,4) == 1) & (index(:,6) == 1);

    % Vectorized HT evaluation of the current Fourier coefficient.
    f_val = ht.evaluate_index( ...
        f_preT, ...
        x_extend{1}(n_ghost + index(:,1), 2), ...
        index(:,2), ...
        x_extend{2}(n_ghost + index(:,3), 2), ...
        index(:,4), ...
        x_extend{3}(n_ghost + index(:,5), 2), ...
        index(:,6));

    % Get the subset of nonzero modes for fast batch interpolation.
    valid_idx = ~zero_mask;
    N_valid = sum(valid_idx);

    phi_val = zeros(N, 1);

    if N_valid > 0
        idx_x = index(valid_idx, 1);
        idx_y = index(valid_idx, 3);
        idx_z = index(valid_idx, 5);

        % Pull matching wave modes and format them as column vectors.
        k1_vec = k_mod_1(index(valid_idx, 2)); k1_vec = k1_vec(:);
        k2_vec = k_mod_2(index(valid_idx, 4)); k2_vec = k2_vec(:);
        k3_vec = k_mod_3(index(valid_idx, 6)); k3_vec = k3_vec(:);

        % Vectorized phase-shift query.
        phi_val(valid_idx) = get_phi_clamped_vec_3D( ...
            phi_ht, phix_ht, phi_cross, ...
            idx_x, idx_y, idx_z, x_extend, ...
            k1_vec, k2_vec, k3_vec, ...
            H, h_mesh, N_mesh, n_ghost);
    end
    
    % Assemble the updated Fourier coefficient.
    f_new = zeros(N, 1);
    f_new(valid_idx) = f_val(valid_idx) .* exp(1i/H * dt .* phi_val(valid_idx));
end
