function phihalf = get_phi_clamped_vec_3D(phi_ht, phix_ht, phi_cross, ...
                                          idx_x, idx_y, idx_z, x_extend, ...
                                          k1_vec, k2_vec, k3_vec, H, h_mesh, ...
                                          N_mesh, n_ghost)

    % Assumes h_mesh follows [dx, dvx, dy, dvy, dz, dvz]
    dx = h_mesh(1);
    dy = h_mesh(3);
    dz = h_mesh(5); 

    phi_p = eval_dir_clamped_3D( +H/2, k1_vec, k2_vec, k3_vec, dx, dy, dz, ...
                                 idx_x, idx_y, idx_z, ...
                                 phi_ht, phix_ht, phi_cross, x_extend, n_ghost, N_mesh);

    phi_m = eval_dir_clamped_3D( -H/2, k1_vec, k2_vec, k3_vec, dx, dy, dz, ...
                                 idx_x, idx_y, idx_z, ...
                                 phi_ht, phix_ht, phi_cross, x_extend, n_ghost, N_mesh);

    phihalf = phi_m - phi_p;
end